[project]
name = "basic-react-agent"
version = "0.1.0"
description = "A super simple setup of a ReAct agent"
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.66.0",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
]
